### ISSUE TITLE
amplify init fails

### ISSUE THREAD

**Issue by gannaramu** [matwerber1/aws-amplify-react-toolkit#1]
I get the following error after running the command: ``` amplify init ```. Could you let me know what could have gone wrong?

![image](https://user-images.githubusercontent.com/12237488/97775340-6b210c80-1b25-11eb-831f-9a0236311a09.png)

**Comment by matwerber1** [comment]
Hi - Is this your first time using the Amplify CLI? 

If so, you will also need to run `amplify configure` per the docs here:
https://docs.amplify.aws/cli/start/install#install-the-amplify-cli

I will update my readme with this. Let me know if it helps?

**Comment by gannaramu** [comment]
Hello Mat, till now I was using a IAM credential which had administrator access. I also tried creating a new IAM role but still I face the same issue. Could you let me know what else I am doing wrong.

![image](https://user-images.githubusercontent.com/12237488/97788844-8cafe180-1b81-11eb-8994-ef0415dcc731.png)

**Comment by gannaramu** [comment]
Hello Mat,
 I am able to run the ``` amplify init ``` from a different directory. But if I try to run it from the cloned repository I get access denied. Do I need to change anything else?

**Comment by gannaramu** [comment]
I also see the [team-provider-info.josn](https://github.com/matwerber1/aws-amplify-react-toolkit/blob/master/amplify/team-provider-info.json) file which has links to your AWS account do you think this could be the reason?
